### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by VamshikShetty** [Venka97/Skin-cancer-image-classification#1]
Can I get the link to the dataset of skin cancer?

**Comment by Venka97** [comment]
Send me an e-mail and I'll upload the dataset on google drive.

**Comment by VamshikShetty** [comment]
vamshikdshetty@gmail.com
Thanks a lot

**Comment by Venka97** [comment]
https://drive.google.com/drive/folders/1kLRnb4jg6E0ivm9O4BwgnnAFqS37ABIo?usp=sharing

**Comment by Soukaina388** [comment]
could you please send the images folder to my mail ID: bouhalisoukaina1997@gmail.com
